Repository paketo-buildpacks/encrypt-at-rest, pull requests merged in 2022-08, with the labels that each got.

#114 Bump dependencies
  .gitignore
  README.md
  go.mod
  go.sum
Labels: semver:patch, type:bug

#119 Update Pipeline to 1.25.2
  .github/pipeline-version
  .github/workflows/pb-create-package.yml
  .github/workflows/pb-minimal-labels.yml
  .github/workflows/pb-synchronize-labels.yml
  .github/workflows/pb-tests.yml
  .github/workflows/pb-update-draft-release.yml
  .github/workflows/pb-update-go.yml
  .github/workflows/pb-update-pipeline.yml
Labels: type:task, semver:patch

#121 Bump crypto & sys dependencies
  go.mod
  go.sum
Labels: semver:patch, type:dependency-upgrade

#126 Implement RFC 0050: Rename Buildpack
  README.md
  buildpack.toml
Labels: type:task, semver:patch
